### PR TITLE
Update PothosFlow submodule.

### PR DESCRIPTION
**Pull request by eduardosm**
Fixes https://github.com/pothosware/PothosFlow/issues/196

### CODE REVIEW

**Comment by guruofquality** [comment]
Theres a little ./sync_toolkits script that I ran, and committed the result. There were several submodule updates

**Comment by eduardosm** [comment]
Thanks, I didn't know there was that script

**Comment by gvanem** [comment]
> Theres a little ./sync_toolkits script that I ran, and committed the result. 

I was hit by the same "`error: cannot 'dynamic_cast ...` on the file `gui/MessageWindow/LoggerChannel.cpp`. After running that script, that file remains the same. But the file `flow/MessageWindow/LoggerChannel.cpp` is correct for my Poco:
```c
LoggerChannel::LoggerChannel(QObject *parent):
    QObject(parent),
    _logger(Poco::Logger::get("")),
    _oldLevel(_logger.getLevel()),
    #if POCO_VERSION < 0x010A0000
    _splitter(dynamic_cast<Poco::SplitterChannel *>(_logger.getChannel()), true)
    #else
    _splitter(_logger.getChannel().cast<Poco::SplitterChannel>())
    #endif
{
```

So can you help on keeping all these Repos and Sub-modules up-to-date?

**Comment by guruofquality** [comment]
the pothos-flow submodule should be up to date with this change, but you have to run `git submodule update` to get git to sync them to the checked in commits, or alternatively that bash script

**Comment by gvanem** [comment]
Okay. It seemed my problem was that the once `PothosGui` repo was renamed to `PothosFlow`.

**Pull request closed without merging**
