### PR TITLE
HostInfo: added field to list available SIMD architectures on host device

### PR DESCRIPTION
**Pull request by ncorgan**
* Internally uses libsimdpp detection code (BSL), converts to string vector

### CODE REVIEW

**Comment by guruofquality** [comment]
Can https://github.com/p12tic/libsimdpp be a git submodule?

**Comment by ncorgan** [comment]
Sure, I just wasn’t sure if it was worth it for one file, especially since that’s not the library in my SIMD proposal. Simple to do though.

**Comment by guruofquality** [comment]
> Sure, I just wasn’t sure if it was worth it for one file, especially since that’s not the library in my SIMD proposal. Simple to do though.

Its a few files in a directory, easier to keep up to date if its a submodule. It might help with packaging to not include the sources of other projects when possible.

I would tag the repo before adding something like this

Minus the one API header call, it could be implemented as a runtime loaded module, if for some reason that was useful.

**Comment by ncorgan** [comment]
Sounds good. I'll start a SIMD branch with this stuff in place. My thoughts are that this branch would have:
 * This new HostInfo field
 * The simdpp submodule
 * The CMake fanciness we're talking about here: https://github.com/pothosware/PothosBlocks/pull/63

PothosBlocks and PothosComms could have next-esque branches with the implementations I've done, and we'll have it call into the new CMake stuff as it develops. And it all comes together for the tag?

**Comment by ncorgan** [comment]
Closing. Testing a simpler solution without a full additional submodule.

**Pull request closed without merging**
