### PR TITLE
Exception: className() returns demangled name

### PR DESCRIPTION
**Pull request by ncorgan**

### CODE REVIEW

**Comment by ncorgan** [comment]
While it's evident from looking at it, it's worth noting that this is an ABI break for 0.7.

**Comment by guruofquality** [comment]
I'm thinking theres got to be a static way to get that string, its fixed with the typeinfo afterall

**Comment by ncorgan** [comment]
Maybe store the output of typeInfoToString in a static const string inside className and return that c_str()?

Putting this inside the IMPLEMENT macro and base Exception class should cover it.

I’m a few hours away from home in Channelview for the weekend, so I can’t do it myself. I get back Sunday night, so I can do it then, or you can and just delete my branch.

**Comment by guruofquality** [comment]
Does this do it? https://github.com/pothosware/PothosCore/tree/exception_demangle_class_name

**Comment by ncorgan** [comment]
That looks right. I’m not in a position to test it, though.

**Comment by guruofquality** [comment]
i cherry picked this one: https://github.com/pothosware/PothosCore/commit/a32b42415f7838685105e24f9653cc65f891180d

**Pull request closed without merging**
